addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.1.10")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.3.1")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"          % "0.5.0")
addSbtPlugin("net.virtual-void"          % "sbt-dependency-graph" % "0.10.0-RC1")
addSbtPlugin("org.wartremover"           % "sbt-wartremover"      % "2.4.3")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"           % "4.0.0")
