name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        java-package: jdk
        architecture: x64
        redis version: '5'
    - uses: zhulik/redis-action@v1.0.0
      with:
        redis version: '5'
    - run: |
        curl https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt > sbt && chmod +x sbt
        ./sbt +test
