name: publish

on:
  push:
    branches:
      - master
  pull_request:
    types: []


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: zulu@1.8
    - uses: coursier/cache-action@v3
    - run: |
        sbt +publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

