name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: zulu@1.8
    - uses: coursier/cache-action@v3
    - uses: zhulik/redis-action@v1.0.0
      with:
        redis version: '5'
    - run: |
        sbt +test

